name: OOTB Push base language translations to Lokalise
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'App version'
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Lokalise
        uses: lokalise/lokalise-push-action@v4.0.0
        with:
          api_token: ${{ secrets.LOKALISE_TOKEN }}
          project_id: ${{ secrets.LOKALISE_PROJECT_ID }} 
          translations_path: |
            retail/src/main/res/values
            retail/src/dev/rest/values
          name_pattern: "strings_*.xml"
          base_lang: en
          file_ext: xml
          file_format: xml
          flat_naming: false
          use_tag_tracking: true
          rambo_mode: false
          additional_params: >
            {
              "tags": ["${{ github.event.inputs.version }}"]
            }

      - name: Debug secrets presence
        run: |
          echo "Project ID length: ${#LOKALISE_PROJECT_ID}"
          echo "Token length: ${#LOKALISE_TOKEN}"
        env:
          LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
          LOKALISE_TOKEN: ${{ secrets.LOKALISE_TOKEN }}     

