name: OOTB Pull changed translations from Lokalise

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull from Lokalise
        uses: lokalise/lokalise-pull-action@v4.0.0
        with:
          api_token: ${{ secrets.LOKALISE_TOKEN }}
          project_id: ${{ secrets.LOKALISE_PROJECT_ID }}
          base_lang: en
          always_pull_base: true
          translations_path: "retail/src/main/res/values*"
          file_format: xml
          file_ext: xml
          skip_include_tags: true
          pr_title: "Update translations for retail-usa"
          pr_body: "This PR contains the latest translations from Lokalise for retail-usa."
          pr_labels: "translations,lokalise"
          git_commit_message: "chore: update translations for retail-usa"
