name: OOTB Push base language translations to Lokalise
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Lokalise
        uses: lokalise/lokalise-push-action@v4.0.0
        with:
          api_token: ${{ secrets.LOKALISE_TOKEN }}
          project_id: ${{ secrets.LOKALISE_PROJECT_ID }} 
          base_lang: en
          translations_path: "retail/src/main/res"
          file_ext: xml
          name_pattern: "values*/strings.xml"
          file_format: xml
          flat_naming: false

      - name: Debug secrets presence
        run: |
          echo "Project ID length: ${#LOKALISE_PROJECT_ID}"
          echo "Token length: ${#LOKALISE_TOKEN}"
        env:
          LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
          LOKALISE_TOKEN: ${{ secrets.LOKALISE_TOKEN }}     

